---

- name: Install pip
  apt:
    pkg: python-pip
    state: latest

- name: Install awscli
  pip:
    name: awscli
    state: latest

- name: Enable autocomplete
  shell: complete -C aws_completer aws
  ignore_errors: true
  changed_when: false